### ISSUE TITLE
Extract to procedure is not available after installing Pre-Release version 

### ISSUE THREAD

**Issue by JonFjolnirAlbertsson** [DavidFeldhoff/al-codeactions#164] opened 2023-09-29 10:45 UTC
After installing Pre-Release version of AL Language extension, Extract to procedure is not available. I have tried to change back from Pre-Release but it does not help.

**Comment by JuricaB** [comment] 2023-10-01 20:35
Can confirm the issue. I also tried:
- uninstalling and reinstalling al-codeactions
- uninstalling and reinstalling AL language

**Comment by sergioramos83** [comment] 2023-10-02 11:49
For me, it stopped working while on the release version... Switched to the Pre-Release version and the problem remains. I have executed the same steps as mentioned by JuricaB but had no success in making it work again.
Hope it can be solved because it's an interesting feature.

**Comment by DavidFeldhoff** [comment] 2023-10-02 11:58
Thanks for your input guys. Unfortunately, I cannot reproduce it and am therefore stepping in the dark. I tried it with the base app, so I think it's not a sizing issue. Do you have any hints for me? Is there maybe an error in the "Output -> Extension Host"? 

https://github.com/DavidFeldhoff/al-codeactions/assets/53570297/c08fa313-43ce-4441-a08f-d3d7a0e50bac

**Comment by sergioramos83** [comment] 2023-10-02 14:15
Looking into Extension Host i don't see any problem with your extension...
![image](https://github.com/DavidFeldhoff/al-codeactions/assets/13440034/43a4f606-da0d-4afe-8030-7a4edbb536c0)

Yet I still can't use any functionality...

**Comment by DavidFeldhoff** [comment] 2023-10-02 16:36
Hm okay, thanks so far.
Two more questions:
1. If you're trying to use the extract to procedure command, does then something show up in the "Extension Host" log?
2. Is the AZ AL Dev Tools extension working? Im asking it as I just saw that he recompiled his solution today for BC23. I did not look further into what he did and why he needed to do it, but if his extention crashes, my extension most probably fails as well as I'm quite dependent on his API. But that issue would disappear then hopefully directly as soon as he releases his update.

**Comment by sergioramos83** [comment] 2023-10-02 17:32
Hi David,

I figured out that i only have this problem when working in a workspace... if i open a folder of a project i can use the extension normally... So I'm questioning if the problem is on my side which i have doubts about because I've been using your extension for a long time now and with workspaces... Maybe some recent update of VSCode... I'll try to investigate a bit further... Thank you!

**Comment by JuricaB** [comment] 2023-10-02 19:55
@DavidFeldhoff 
- no code actions are available when selecting code while working in workspace. 
- AZ AL Dev Tools v3.0.50
- AL Language v12.0.875970

VS Code details:
Version: 1.82.3 (system setup)
Commit: fdb98833154679dbaa7af67a5a29fe19e55c2b73
Date: 2023-10-02T10:51:22.294Z
Electron: 25.8.1
ElectronBuildId: 24153832
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by JohanCarlstedt** [comment] 2023-10-03 12:16
Seems like this issue occur after updating to latest VS Code.

**Comment by DavidFeldhoff** [comment] 2023-10-04 06:27
Thanks again for your hints. I updated my VS Code now as well and tried again to reproduce it. I tried it
- with a workspace with the latest AL Preview version (v13.0.864697), AZ AL Dev Tools (v3.0.50), AL CodeActions (v1.0.29)
- with a workspace with the latest released AL version (v12.0.875970), AZ AL Dev Tools (v3.0.50), AL CodeActions (v1.0.29)
- with a folder with the latest AL Preview version (v13.0.864697), AZ AL Dev Tools (v3.0.50), AL CodeActions (v1.0.29)
- with a folder with the latest released AL version (v12.0.875970), AZ AL Dev Tools (v3.0.50), AL CodeActions (v1.0.29)

but unfortunately I failed to reproduce it everywhere.

Version: 1.82.3 (user setup)
Commit: fdb98833154679dbaa7af67a5a29fe19e55c2b73
Date: 2023-10-02T10:51:22.294Z
Electron: 25.8.1
ElectronBuildId: 24153832
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

Can someone send me a project with which I should be able to reproduce it?

**Comment by DavidFeldhoff** [comment] 2023-10-04 08:57
Short update: I could finally reproduce it. Now trying to find a solution..

**Comment by DavidFeldhoff** [comment] 2023-10-06 19:38
I think I found the issue together with Andrzej. It might happen if there is a folder in the workspace which does not have an app.json, can you confirm that? If that's the case, Andrzej (AZ AL Dev Tools) is fixing it on his site. 
So it has nothing to do with the AL version as far as i can see, but there was a (from AL CodeActions POV) breaking change in one of the latest AZ AL Dev Tools updates.
I hope that's it and that you're after the update able to work again without issues :)

**Comment by sergioramos83** [comment] 2023-10-09 10:19
Hi David,

I can confirm that's the issue... as soon as i opened a workspace in which all folders have an app.json it worked normally...

Waiting for the update :)

Thank you!

**Comment by M4fin** [comment] 2023-10-10 10:10
Hi All,

I have a same problem, but i find another workaround.
Try to install version 3.0.47 of AZ AL Dev Tools/AL Code Outline.
This works for me.

**Comment by DavidFeldhoff** [comment] 2023-10-10 16:00
I decided to do the fix on my site now. The release v1.0.30 should be working fine again entirely. Would be happy if you could confirm that.

**Comment by JuricaB** [comment] 2023-10-10 19:53
@DavidFeldhoff  thank you so much! Confirmed working with latest update on multi-workspace with missing app.json in one of the folders.

**Comment by sergioramos83** [comment] 2023-10-11 10:19
@DavidFeldhoff I confirm it's working like stated by @JuricaB. Thank you!

**Comment by DavidFeldhoff** [comment] 2023-10-13 06:10
Great, thanks for confirming this and helping to find the issue ! I'm going to close this one now. In case there's something still open, feel free to reopen or create a new issue :)

**Closed** 2023-10-13 06:10 UTC
Labels: released
